### ISSUE TITLE
check the 'status' doesn't work

### ISSUE THREAD

**Issue by tido-** [jekader/hostapd-rtl#2]
update-rc.d -f hostapd defaults 

root@superPi:~# update-rc.d -f hostapd defaults
update-rc.d: using dependency based boot sequencing

root@superPi:~# /etc/init.d/hostapd status
root@superPi:~#

no changes

root@superPi:~# service hostapd status
root@superPi:~#

both commands do not work.

**Comment by jekader** [comment]
Please check the README:
https://github.com/jekader/hostapd-rtl/blob/master/README.md#use

this is supposed to be disabled until you uncomment the line in /etc/default/hostapd

**Comment by jekader** [comment]
I also fixed init file permissions so now the init script should be added properly at install time.
