### ISSUE TITLE
openwrt 300-noscan.patch

### ISSUE THREAD

**Issue by matjadoel** [jekader/hostapd-rtl#6]
hi jekader,

just info, could you update your repo to include new 300-noscan.patch (openwrt). according this url https://dev.openwrt.org/browser/trunk/package/network/services/hostapd/patches/300-noscan.patch it was updated 2 days ago.

**Comment by jekader** [comment]
Thanks for informing me! I will look into it and apply this patch.

**Comment by jekader** [comment]
new patch applied
