### ISSUE TITLE
 hostapdioctl[RTL_IOCTL_HOSTAPD]: Operation not supported

### ISSUE THREAD

**Issue by Freundschaft** [jekader/hostapd-rtl#7]
I get  hostapdioctl[RTL_IOCTL_HOSTAPD]: Operation not supported
when running service hostapd start

am I doing something wrong? I am using the RB1

**Comment by jekader** [comment]
I also get this when starting hostapd. Doesn't seem to influence anything so just ignore this message.

**Comment by Freundschaft** [comment]
alright, in order to refresh the wifi settings? I just need to run service hostapd restart? or do I need to do an ifconfig wlan0 down/up as well?

**Comment by jekader** [comment]
Just restart hostapd.

**Comment by Freundschaft** [comment]
thanks!
