### ISSUE TITLE
A few general issues

### ISSUE THREAD

**Issue by AaronMcHale** [jekader/hostapd-rtl#8]
Hi, so I'm using Arch on a Raspberry Pi and decided to build hostapd using the components in this repository, I noticed while running make I get the following messages:

>  CC  ../src/ap/ctrl_iface_ap.c
>  CC  ../src/ap/wpa_auth_ft.c
> ../src/drivers/driver_rtw.c: In function 'rtl871x_set_hidden_ssid_ops':
> ../src/drivers/driver_rtw.c:1336:23: warning: unused variable 'hapd' [-Wunused-variable]
>  struct hostapd_data *hapd = drv->hapd;
>                       ^
> ../src/drivers/driver_rtw.c: In function 'rtl871x_set_beacon_ops':
> ../src/drivers/driver_rtw.c:1392:10: warning: assignment discards 'const' qualifier from pointer target >type [-Wdiscarded-qualifiers]
>  ssid_ie = get_ie((params->head+24+12), (params->head_len-24-12), WLAN_EID_SSID);
>          ^
>  CC  ../src/drivers/driver_rtw.c
>  CC  ../src/drivers/driver_nl80211.c

It doesn't seem to cause an issue but was hoping someone might have an idea.  Additionally the 300-noscan patch doesn't seem to work, when I start hostapd I get the following:

> Configuration file: hostapd.conf
> drv->ifindex=4
> l2_sock_recv==l2_sock_xmit=0x0xd10678
> wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
> wlan0: interface state COUNTRY_UPDATE->HT_SCAN
> Failed to request a scan of neighboring BSSes ret=-1 (Operation not permitted)
> wlan0: interface state HT_SCAN->DISABLED
> wlan0: AP-DISABLED 
> wlan0: interface state DISABLED->DISABLED
> +rtl871x_sta_deauth_ops, ff:ff:ff:ff:ff:ff is deauth, reason=3
> rtl871x_set_key_ops
> rtl871x_set_key_ops
> rtl871x_set_key_ops
> rtl871x_set_key_ops
> wlan0: AP-DISABLED 
> hostapd_free_hapd_data: Interface wlan0 wasn't started
> ELOOP: remaining socket: sock=6 eloop_data=0xd10708 user_data=(nil) handler=0x5e52c

The above happens with the following config setting:

> ht_capab=[HT40+][SHORT-GI-40]

Any help with this would be great, thanks.
Aaron

**Comment by jekader** [comment]
Hi, the code is not mine so don't blame me for compiler warnings. They can be ignored. Patches welcome to remove code that causes them.

As for the second issue - what's the full config file? Are you sure you have noscan=1 in it?
Also, what's the kernel you're using and where did you get the 8192cu driver?

**Comment by AaronMcHale** [comment]
Ah, that may be the problem, I do not have noscan=1 in the config, didn't realise I needed that.  Added it, works fine now.

And I wasn't blaming you :), just wondered if anyone had come across a fix for it, I've opened an issue over at the GitHub Repo for the driver https://github.com/pritambaral/hostapd-rtl871xdrv/issues/5

Do you think it would be a good idea to mention on the readme to enable "noscan=1" for cases like myself where users already have a config file?

Thank you

**Comment by jekader** [comment]
This is not the only option one needs to make hostapd-rtl work. That's why a sample config with all required options is provided.

As for the driver code - it was written by realtek years ago. Not sure if it's maintained any more but good luck with fixing that in the repo I used as upstream. Closing this issue.

**Comment by AaronMcHale** [comment]
Ah ok thanks
